## Numpy tutorial for beginner by freeCodeCamp.org
Below is the URL for the tutorial
https://www.youtube.com/watch?v=QUT1VHiLmmI

## Load in Numpy (remember to pip install numpy first)

In [1]:
import numpy as np

## The Basics

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
#Get Dimension
a.ndim

1

In [7]:
b.ndim

2

In [8]:
#Get Shape
b.shape

(2, 3)

In [9]:
#Get Type
a.dtype

dtype('int32')

In [10]:
#Get Size
a.itemsize

4

In [11]:
#Get total size
a.size

3

In [12]:
a.nbytes

12

 ## Accessing/Changing specific elements, rows, columns, etc

In [14]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
a.shape

(2, 7)

In [18]:
#get a specific element [r,c]
a[1,-2]
a[1,5]

13

In [19]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
#get a specific column
a[:,2]

array([ 3, 10])

In [21]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [22]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [24]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [25]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3-D example

In [27]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
#Get specific element(work outside in)
#i want to get 4
b[0,1,1]

4

In [29]:
#replace
b[:,1,:]=[[9,9],[8,8]]

In [30]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [33]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [38]:
#Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [40]:
#Any other number (full like)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [41]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [43]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.51607315, 0.26710097],
       [0.99049366, 0.94484748],
       [0.43154309, 0.93571923],
       [0.87450994, 0.94268793]])

In [45]:
np.random.random_sample(a.shape)

array([[0.96580365, 0.87793935, 0.30191723, 0.61458146, 0.94305626,
        0.8502062 , 0.13141949],
       [0.68183768, 0.56183395, 0.61008824, 0.18506576, 0.21601137,
        0.58526609, 0.95679377]])

In [47]:
#random integer values
np.random.randint(7)

6

In [48]:
np.random.randint(7,size=(3,3))


array([[3, 4, 1],
       [2, 0, 2],
       [1, 5, 0]])

In [52]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
#repeat an array
#repeat row
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [60]:
#repeat column
arr=np.array([[1,2,3]])
r2=np.repeat(arr,3,axis=1)
print(r2)

[[1 1 1 2 2 2 3 3 3]]


#### Exercise 1
Recreate the matrix below
![title](exercise1.png)

In [70]:
a=np.ones((5,5),dtype='int32')
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [74]:
a[1:4,1:4]=0
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [75]:
a[2,2]=9
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Be careful when copying arrays!!!!

In [82]:
a=np.array([1,2,3])
b=a
b

array([1, 2, 3])

In [85]:
#replace 1 with 100
b[0]=100
b

array([100,   2,   3])

In [87]:
#!!!!!!!!!!!Look at a!!!!!
a

array([100,   2,   3])

In [89]:
#What should have been done is...... to copy
a=np.array([1,2,3])
b=a.copy()
b

array([1, 2, 3])

In [91]:
b[0]=100
b

array([100,   2,   3])

In [93]:
#a remains the same
a

array([1, 2, 3])

## Mathematics

In [95]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [96]:
a+2

array([3, 4, 5, 6])

In [97]:
a-2

array([-1,  0,  1,  2])

In [98]:
a*2

array([2, 4, 6, 8])

In [99]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [100]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [101]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [102]:
#for a lot more (https://docs.scipy.org/doc/numpy/reference/rontines.math.html)

#### Linear Algebra

In [105]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [107]:
#matrix multiply function
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [110]:
#Find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

In [111]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

#Determinant
#Trace
#Singular Vector Decomposition
#Eigenvalues
#Matrix Norm
#Inverse
#Etc...

#### Statistics

In [112]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
np.min(stats)

1

In [115]:
np.max(stats)

6

In [117]:
#axis=0 columns; axis=1 rows
np.min(stats,axis=0)

array([1, 2, 3])

In [118]:
np.max(stats,axis=1)

array([3, 6])

### Reorganizing Arrays

In [121]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [124]:
after=before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [126]:
after=before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [128]:
#Vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
#Horizontal stack
h1=np.ones((2,4))
print(h1)
h2=np.zeros((2,2))
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [130]:
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [132]:
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [134]:
filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### Boolean Masking and Advanced Indexing

In [136]:
#I want to find which value is more than 50
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [138]:
#masking: returns values more than 50
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [140]:
## you can index with a list in NumPy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [141]:
#figure out any of the values in the filedata column is greater than 50
#means if any of the column have a value of >50 it will show true
 np.any(filedata>50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [142]:
np.all(filedata>50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [143]:
#multiple conditions
((filedata>50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [144]:
~((filedata>50) & (filedata<100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

## Quiz 1
index the blue box part of the matrix
![title](quiz1.png)

In [169]:
data=np.arange(1,31).reshape(6,5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [172]:
#blue
data[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [175]:
#green
data[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [176]:
#red
data[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])